### ISSUE TITLE
Jobs are not starting even if the server_wide_modules are loaded (from odoo.conf).

### ISSUE THREAD

**Issue by KamranValijonov** [OCA/queue#446]
## Module
Strange behavior in queue_job for odoo v14.

## Describe the bug
I am running some methods with `with_delay` option. When I enter to jobs dashboard, I can see that the jobs appeared there, but they are always in PENDING state.

I am running odoo in docker-compose with a default command of odoo image.

Partial content of docker-compose.yml
```
version: '3.7'

services:
  odoo:
    container_name: odoo
    hostname: odoo
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8069"
      - "8072:8072"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/robot_analytics_bigquery.json
    volumes:
      - ../../config:/etc/odoo/
      - ../../enterprise:/enterprise/
      - ../../modules:/mnt/extra-addons
      - ../../requirements.txt:/requirements.txt
      - ../../stats/:/temp/
      - ${LOCAL_GOOGLE_APPLICATION_CREDENTIALS}:/robot_analytics_bigquery.json
```

Full content of odoo.conf:
```
[options]
addons_path = /mnt/extra-addons,/enterprise
admin_passwd = password
csv_internal_sep = ,
data_dir = /var/lib/odoo
db_host = database
db_maxconn = 400
db_name = odoo_dev
db_password = odoo_admin
db_port = 5432
db_sslmode = prefer
db_template = template1
db_user = odoo_admin
dbfilter = ^.*$
debug_mode = False
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = 8069
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 9999
limit_time_real = 9999
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = [':INFO']
log_level = info
logfile =
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = False
osv_memory_count_limit = False
pg_path =
pidfile =
proxy_mode = True
reportgz = False
screencasts =
screenshots = /tmp/odoo_tests
server_wide_modules = base,web,queue_job,accel
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file =
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path =
without_demo = False
workers = 9
xmlrpcs = True
xmlrpcs_interface =
xmlrpcs_port = 8069

[queue_job]
channels = root:9
```
